vim.keymap.set("n", "<Leader>0", "<cmd>Telescope oldfiles<cr>", { desc = "Telescope: Lists previously open files" })
vim.keymap.set("n", "<Leader>o", "<cmd>Telescope find_files<cr>", { desc = "Telescope: Open files" })
vim.keymap.set("n", "<Leader>m", "<cmd>Telescope marks<cr>", { desc = "Telescope: Lists vim marks" })
vim.keymap.set("n", "<Leader><Leader>", "<cmd>Telescope<cr>", { desc = "Telescope: Open builtin function" })
vim.keymap.set("n", "<Leader>d", "<cmd>Telescope diagnostics<cr>", { desc = "Telescope: Lists diagnostics" })
vim.keymap.set("n", "<Leader>a", "<cmd>Telescope lsp_document_symbols<cr>", { desc = "Telescope: List LSP symbols" })
vim.keymap.set("n", "<Leader>l", "<cmd>Telescope buffers<cr>", { desc = "Telescope: Lists buffers" })
