require("modules.ui.bufferline")()
require("modules.ui.feline")()
require("modules.ui.filemanager")()
require("modules.ui.indentline")()
require("modules.ui.telescope")()
require("modules.ui.treesitter")()
require("modules.ui.colorizer")()
