require("configs.ui.bufferline")()
require("configs.ui.feline")()
require("configs.ui.filemanager")()
require("configs.ui.indentline")()
require("configs.ui.telescope")()
require("configs.ui.treesitter")()
require("configs.ui.colorizer")()
