vim.opt.cursorcolumn = true
vim.opt.cursorline = true
vim.opt.fillchars = {
	horiz = "━",
	horizup = "┻",
	horizdown = "┳",
	vert = "┃",
	vertleft = "┫",
	vertright = "┣",
	verthoriz = "╋",
	eob = " ",
}
vim.opt.listchars = {
	tab = "  ",
	space = " ",
}
vim.opt.foldlevel = 0
vim.opt.linespace = 0
vim.opt.number = false
vim.opt.pumblend = 10
vim.opt.report = 2
vim.opt.scrolloff = 5
vim.opt.sidescrolloff = 10
vim.opt.shortmess = "atToOcF"
vim.opt.showcmd = false
vim.opt.showmode = false
vim.opt.wildmenu = true
vim.opt.wildmode = "full"
vim.opt.wildoptions = "pum"
vim.opt.winblend = 0
