local options = {
    backends = { "treesitter", "lsp", "markdown" },
    close_behavior = "auto",
    default_bindings = true,
    default_direction = "prefer_right",
    -- filter_kind = {
    --     "File",
    --     "Module",
    --     "Namespace",
    --     "Package",
    --     "Class",
    --     "Method",
    --     "Property",
    --     "Field",
    --     "Constructor",
    --     "Enum",
    --     "Interface",
    --     "Function",
    --     "Variable",
    --     "Constant",
    --     "String",
    --     "Number",
    --     "Boolean",
    --     "Array",
    --     "Object",
    --     "Key",
    --     "Null",
    --     "EnumMember",
    --     "Struct",
    --     "Event",
    --     "Operator",
    --     "TypeParameter",
    -- },
    filter_kind = false,
    highlight_mode = "split_width",
    highlight_closest = true,
    highlight_on_hover = true,
    link_folds_to_tree = true,
    link_tree_to_folds = true,
    manage_folds = true,
    max_width = { 40, 0.2 },
    width = 30,
    min_width = 20,
    close_on_select = false,
    show_guides = true,
    update_events = "TextChanged,InsertLeave",
    guides = {
        -- When the child item has a sibling below it
        mid_item = "├─",
        -- When the child item is the last in the list
        last_item = "└─",
        -- When there are nested child guides to the right
        nested_top = "│ ",
        -- Raw indentation
        whitespace = "  ",
    },
}

require("aerial").setup(options)
require("telescope").load_extension("aerial")
