local options = {
    backends = { "lsp", "markdown" },
    layout = {
        default_direction = "prefer_right",
        placement = "edge",
    },
    filter_kind = {
        "Array",
        "Class",
        "Constructor",
        "Enum",
        "Field",
        "Function",
        "Interface",
        "Method",
        "Module",
        "Object",
        "Struct",
        "TypeParameter",
    },
    highlight_mode = "full_width",
    highlight_closest = true,
    highlight_on_hover = false,
    link_folds_to_tree = true,
    max_width = 0.3,
    min_width = 0.2,
    nerd_font = "auto",
    update_events = "TextChanged,InsertLeave",
    float = {
        border = "single",
        relative = "editor",
        max_height = 0.9,
        height = nil,
        min_height = { 8, 0.4 },
    },
    show_guides = true,
    guides = {
        mid_item = "├─",
        last_item = "└─",
        nested_top = "│ ",
        whitespace = "  ",
    },
}

require("aerial").setup(options)
